platform :ios, '9.0'
use_frameworks!

def shared_pods
  pod 'MTDataAPI-SDK'
  pod 'JSQMessagesViewController'
  pod 'SDWebImage'
end

target 'ChatApp' do
    shared_pods
end

target 'ChatAppTests' do
    shared_pods
end

target 'ChatAppUITests' do
    shared_pods
end
